name: Lint system_metrics_collector
on:
  pull_request:

jobs:
  ament_lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, flake8, pep257, uncrustify, xmllint]
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros2@0.0.5
      - uses: ros-tooling/action-ros2-lint@0.0.3
        with:
          linter: ${{ matrix.linter }}
          package-name: system_metrics_collector
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: errata-ai/vale-action@v1.0.3
      with:
        styles: |
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          https://github.com/errata-ai/Google/releases/latest/download/Google.zip
        config:
          https://raw.githubusercontent.com/ros-tooling/system_metrics_collector/master/.vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
